services:
  app:
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    ports:
      - "8080:80"    # Frontend (Nginx)
    env_file:
      - .env
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres-data: